@startuml

class Father {
  - #name: String
  - children: List<Children>
  + {constructor} Father(name: String)
  + getFatherName(): String
}

class Mother {
  - #name: String
  + {constructor} Mother(name: String)
  + getMotherName(): String
}

class Children {
  - #name: String
  - #father: Father
  - #mother: Mother
  + {constructor} Children(name: String, father: Father, mother: Mother)
  + getChildrenName(): String
  + getFather(): Father
  + getMother(): Mother
}

Father *-- "1..*" Children: children
Mother *-- "1..*" Children: mother

@enduml

